### ISSUE TITLE
Move tendrl builds from Copr to CentOS repos

### ISSUE THREAD

**Issue by mykaul** [Tendrl/tendrl-ansible#107]
Will remove the extra step of the copr repo, will be aligned with Gluster (and Ceph?) in the storage sig (https://wiki.centos.org/SpecialInterestGroup/Storage)

**Comment by mbukatov** [comment]
I proposed that back in January (I thought that planned CentOS CI setup for pull requests would be a good opportunity for this), but it didn't get priority high enough to be implemented.

Since this is not an issue of tendrl-ansible, so I'm closing this issue now. Also because we don't have a single repository with rpm spec files, I would suggest to post this proposal to tendrl-devel mailing list instead.

**Comment by mykaul** [comment]
Thanks. I've opened it on Tendrl. The main motivation is yet another step to simplify deployment of tendrl.
Right now, it's a bit of a hassle.
