### ISSUE TITLE
tendrl-node-monitoring error on restart

### ISSUE THREAD

**Issue by japplewhite** [Tendrl/tendrl-ansible#11]
I received this error on running site.yml with hard coded variables for etcd/api
ansible-playbook -i gce-hosts -u ajeffrey -b site.yml --limit @site.retry

RUNNING HANDLER [tendrl-storage-node : restart tendrl-node-monitoring] *********
fatal: [stg03]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to start service tendrl-node-monitoring: Job for tendrl-node-monitoring.service failed because start of the service was attempted too often. See \"systemctl status tendrl-node-monitoring.service\" and \"journalctl -xe\" for details.\nTo force a start use \"systemctl reset-failed tendrl-node-monitoring.service\" followed by \"systemctl start tendrl-node-monitoring.service\" again.\n"}
fatal: [stg02]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to start service tendrl-node-monitoring: A dependency job for tendrl-node-monitoring.service failed. See 'journalctl -xe' for details.\n"}

**Comment by mbukatov** [comment]
There are 3 possible root causes of this issue, restart of `tendrl-node-monitoring` could fail because of:

* mistake in tendrl-ansible (eg. typo in name of the service, missing restart handler or something similar) - based on the output, we can immediately rule this option out
* mistake (eg. misconfiguration) in tendrl-ansible, which caused the restart fail indirectly
* bug in tendrl-node-monitoring itself

Which means we need to get more evidence to decide if option 2 or 3 is the answer.

@japplewhite  Do you see anything interesting in logs of tendrl-node-monitoring?

**Comment by japplewhite** [comment]
@mbukatov just logged separate issue - may be the same or not

https://github.com/Tendrl/tendrl-ansible/issues/12

**Comment by mbukatov** [comment]
@Tendrl/qe Did anybody else seen this kind of error recently?

**Comment by mbukatov** [comment]
Based on further investigation, this is not an issue of tendrl-ansible. See  https://github.com/Tendrl/node-agent/issues/519
