### ISSUE TITLE
Can't import ceph cluster

### ISSUE THREAD

**Issue by gelato** [Tendrl/tendrl-ansible#26]
Hello.
First of all this role fails, demanding graphite_ip_address (ok if you set it manually in ceph role).
Secondly - i can't import ceph cluster for some reason (it detects hosts, their role, but as i think it tries to communicate with them as gluster nodes) - i get timeouts all the time.
I noticed dev packages on fedora repo, which have reworked ui and support ceph - is there somewhere a guide how to install that version?

**Comment by mbukatov** [comment]
>  First of all this role fails, demanding graphite_ip_address (ok if you set it manually in ceph role).
> Secondly - i can't import ceph cluster for some reason (it detects hosts, their role, but as i think it tries to communicate with them as gluster nodes) - i get timeouts all the time.

I should have removed the play for `ceph-servers` from the example playbook for [1.5.0 release](https://github.com/Tendrl/documentation/wiki/Tendrl-release-v1.5.0-(summary)) already so that you would not expect ceph features to work. The scope of the project changed recently, with  focus shifting to monitoring of GlusterFS.  While this doesn't mean that we remove all ceph features from the code base completely (we will need them in the future), it doesn't mean that ceph management and monitoring would be usable for the end user with current releases.

> I noticed dev packages on fedora repo, which have reworked ui and support ceph - is there somewhere a guide how to install that version?

Right now, the rpm builds provided by the project is very simple:

* [COPR tendrl/release](https://copr.fedorainfracloud.org/coprs/tendrl/release/) where you can find rpm repository for the last release ([1.5.1](https://github.com/Tendrl/documentation/wiki/Tendrl-release-v1.5.1-(summary)) right now)
* [COPR tendrl/tendrl](https://copr.fedorainfracloud.org/coprs/tendrl/tendrl/) which provides development snapshot builds from master branch

This unfortunately means that when we release new Tendrl version, it's no longer possible to install previous release directly. That said, since version 1.5.1, we do at least snapshot the Installation Guide, so that it's possible to refer to the [Installation Guide for 1.5.1](https://github.com/Tendrl/documentation/wiki/Tendrl-release-v1.5.1-(install-guide)) even when another release comes out.

Besides that, there is a tendrl/dependencies COPR which is needed for both repositories listed above.

**Comment by mbukatov** [comment]
@Tendrl/tendrl-core who from the tendrl team is responsible for communication with ceph folks?

**Comment by r0h4n** [comment]
@gelato Tendrl as of now does not support ceph, please subscribe to this issue for updates as to when Tendrl can support ceph

**Comment by curtbruns** [comment]
Hi - 
Is there a roadmap for Tendrl and when it might support Ceph clusters?  Thanks!

**Comment by mbukatov** [comment]
Based on my current understanding, closing as wontfix.
