### ISSUE TITLE
Installation of notifier service

### ISSUE THREAD

**Issue by cybernth** [Tendrl/tendrl-ansible#33]
Provide support for the installation and configuration of notifier service. More information can be found at https://github.com/Tendrl/notifier/blob/master/doc/source/installation.rst

**Comment by mbukatov** [comment]
@nthomas-redhat is it ok to make configuration of email notifications optional so that it would be possible to install and enable tendrl-notifier without email configuration or should we just skip installation of the whole component when email configuration for notifier is not provided?

Also I guess that enforcing configuration of email notifications doesn't make sense, even though that the documentation seems to imply this.

**Comment by cybernth** [comment]
@mbukatov , Agree with you. Its optional and you should not skip the installation if the email config not provided.

**Comment by mbukatov** [comment]
Fixed by https://github.com/Tendrl/tendrl-ansible/pull/39
