### ISSUE TITLE
Task Install tendrl-apid dependency errors

### ISSUE THREAD

**Issue by andrewlove** [Tendrl/tendrl-ansible#4]
I'm running tendrl-ansible to install tendrl-server on a dedicated VM and tendrl-node on three glusterfs storage servers. Unfortunately I'm getting dependency errors installing the tendrl-apid piece.
The task in question is `Install tendrl-apid` in `install-tendrl.yml`
The ansible error output is:
```TASK [tendrl-server : Install tendrl-apid] *************************************
fatal: [ose-tendrl-001]: FAILED! => {"changed": true, "failed": true, "msg": "Error: Package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch (tendrl-tendrl)\n           Requires: rubygem-bundler >= 1.13.6\n           Installed: rubygem-bundler-1.7.8-3.el7.noarch (@base)\n               rubygem-bundler = 1.7.8-3.el7\nError: Package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch (tendrl-tendrl)\n           Requires: rubygem-mixlib-log >= 1.7.1\nError: Package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch (tendrl-tendrl)\n           Requires: rubygem-etcd\nError: Package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch (tendrl-tendrl)\n           Requires: rubygem-sinatra >= 1.4.5\nError: Package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch (tendrl-tendrl)\n           Requires: rubygem-tilt >= 1.4.1\nError: Package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch (tendrl-tendrl)\n           Requires: rubygem-puma >= 3.6.0\nError: Package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch (tendrl-tendrl)\n           Requires: rubygem-minitest >= 5.9.1\n           Available: rubygem-minitest-4.3.2-29.el7.noarch (base)\n               rubygem-minitest = 4.3.2-29.el7\n", "rc": 1, "results": ["Loaded plugins: fastestmirror\nLoading mirror speeds from cached hostfile\n * base: centos.serverspace.co.uk\n * epel: mirrors.coreix.net\n * extras: mirrors.vooservers.com\n * updates: centos.serverspace.co.uk\nResolving Dependencies\n--> Running transaction check\n---> Package tendrl-api.noarch 0:1.2.3-05_02_2017_19_43_13 will be installed\n--> Processing Dependency: rubygem-activemodel >= 4.2.6 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch\n--> Processing Dependency: rubygem-activesupport >= 4.2.6 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch\n--> Processing Dependency: rubygem-bcrypt >= 3.1.10 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch\n--> Processing Dependency: rubygem-bundler >= 1.13.6 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch\n--> Processing Dependency: rubygem-i18n >= 0.7.0 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch\n--> Processing Dependency: rubygem-minitest >= 5.9.1 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch\n--> Processing Dependency: rubygem-mixlib-log >= 1.7.1 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch\n--> Processing Dependency: rubygem-puma >= 3.6.0 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch\n--> Processing Dependency: rubygem-rack >= 1.6.4 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch\n--> Processing Dependency: rubygem-rack-protection >= 1.5.3 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch\n--> Processing Dependency: rubygem-rake >= 0.9.6 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch\n--> Processing Dependency: rubygem-sinatra >= 1.4.5 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch\n--> Processing Dependency: rubygem-thread_safe >= 0.3.5 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch\n--> Processing Dependency: rubygem-tilt >= 1.4.1 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch\n--> Processing Dependency: rubygem-tzinfo >= 1.2.2 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch\n--> Processing Dependency: rubygem-etcd for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch\n--> Running transaction check\n---> Package rubygem-activemodel.noarch 0:4.2.6-3.el7 will be installed\n--> Processing Dependency: rubygem(builder) for package: rubygem-activemodel-4.2.6-3.el7.noarch\n---> Package rubygem-activesupport.noarch 1:4.2.6-1.el7 will be installed\n---> Package rubygem-bcrypt.x86_64 0:3.1.10-6.el7 will be installed\n---> Package rubygem-i18n.noarch 0:0.7.0-3.el7 will be installed\n---> Package rubygem-rack.noarch 1:1.6.4-2.el7 will be installed\n---> Package rubygem-rack-protection.noarch 0:1.5.3-3.el7 will be installed\n---> Package rubygem-rake.noarch 0:0.9.6-29.el7 will be installed\n---> Package rubygem-thread_safe.noarch 0:0.3.5-2.el7 will be installed\n---> Package rubygem-tzinfo.noarch 0:1.2.2-3.el7 will be installed\n---> Package tendrl-api.noarch 0:1.2.3-05_02_2017_19_43_13 will be installed\n--> Processing Dependency: rubygem-bundler >= 1.13.6 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch\n--> Processing Dependency: rubygem-minitest >= 5.9.1 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch\n--> Processing Dependency: rubygem-mixlib-log >= 1.7.1 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch\n--> Processing Dependency: rubygem-puma >= 3.6.0 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch\n--> Processing Dependency: rubygem-sinatra >= 1.4.5 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch\n--> Processing Dependency: rubygem-tilt >= 1.4.1 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch\n--> Processing Dependency: rubygem-etcd for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch\n--> Running transaction check\n---> Package rubygem-builder.noarch 0:3.1.4-3.el7 will be installed\n---> Package tendrl-api.noarch 0:1.2.3-05_02_2017_19_43_13 will be installed\n--> Processing Dependency: rubygem-bundler >= 1.13.6 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch\n--> Processing Dependency: rubygem-minitest >= 5.9.1 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch\n--> Processing Dependency: rubygem-mixlib-log >= 1.7.1 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch\n--> Processing Dependency: rubygem-puma >= 3.6.0 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch\n--> Processing Dependency: rubygem-sinatra >= 1.4.5 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch\n--> Processing Dependency: rubygem-tilt >= 1.4.1 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch\n--> Processing Dependency: rubygem-etcd for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch\n--> Finished Dependency Resolution\n You could try using --skip-broken to work around the problem\n You could try running: rpm -Va --nofiles --nodigest\n"]}
```

A manual attempt at installing the RPM gives an equivalent:
```yum install tendrl-api
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.serverspace.co.uk
 * epel: mirrors.coreix.net
 * extras: mirrors.vooservers.com
 * updates: centos.serverspace.co.uk
Resolving Dependencies
--> Running transaction check
---> Package tendrl-api.noarch 0:1.2.3-05_02_2017_19_43_13 will be installed
--> Processing Dependency: rubygem-activemodel >= 4.2.6 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch
--> Processing Dependency: rubygem-activesupport >= 4.2.6 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch
--> Processing Dependency: rubygem-bcrypt >= 3.1.10 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch
--> Processing Dependency: rubygem-bundler >= 1.13.6 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch
--> Processing Dependency: rubygem-i18n >= 0.7.0 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch
--> Processing Dependency: rubygem-minitest >= 5.9.1 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch
--> Processing Dependency: rubygem-mixlib-log >= 1.7.1 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch
--> Processing Dependency: rubygem-puma >= 3.6.0 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch
--> Processing Dependency: rubygem-rack >= 1.6.4 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch
--> Processing Dependency: rubygem-rack-protection >= 1.5.3 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch
--> Processing Dependency: rubygem-rake >= 0.9.6 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch
--> Processing Dependency: rubygem-sinatra >= 1.4.5 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch
--> Processing Dependency: rubygem-thread_safe >= 0.3.5 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch
--> Processing Dependency: rubygem-tilt >= 1.4.1 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch
--> Processing Dependency: rubygem-tzinfo >= 1.2.2 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch
--> Processing Dependency: rubygem-etcd for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch
--> Running transaction check
---> Package rubygem-activemodel.noarch 0:4.2.6-3.el7 will be installed
--> Processing Dependency: rubygem(builder) for package: rubygem-activemodel-4.2.6-3.el7.noarch
---> Package rubygem-activesupport.noarch 1:4.2.6-1.el7 will be installed
---> Package rubygem-bcrypt.x86_64 0:3.1.10-6.el7 will be installed
---> Package rubygem-i18n.noarch 0:0.7.0-3.el7 will be installed
---> Package rubygem-rack.noarch 1:1.6.4-2.el7 will be installed
---> Package rubygem-rack-protection.noarch 0:1.5.3-3.el7 will be installed
---> Package rubygem-rake.noarch 0:0.9.6-29.el7 will be installed
---> Package rubygem-thread_safe.noarch 0:0.3.5-2.el7 will be installed
---> Package rubygem-tzinfo.noarch 0:1.2.2-3.el7 will be installed
---> Package tendrl-api.noarch 0:1.2.3-05_02_2017_19_43_13 will be installed
--> Processing Dependency: rubygem-bundler >= 1.13.6 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch
--> Processing Dependency: rubygem-minitest >= 5.9.1 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch
--> Processing Dependency: rubygem-mixlib-log >= 1.7.1 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch
--> Processing Dependency: rubygem-puma >= 3.6.0 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch
--> Processing Dependency: rubygem-sinatra >= 1.4.5 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch
--> Processing Dependency: rubygem-tilt >= 1.4.1 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch
--> Processing Dependency: rubygem-etcd for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch
--> Running transaction check
---> Package rubygem-builder.noarch 0:3.1.4-3.el7 will be installed
---> Package tendrl-api.noarch 0:1.2.3-05_02_2017_19_43_13 will be installed
--> Processing Dependency: rubygem-bundler >= 1.13.6 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch
--> Processing Dependency: rubygem-minitest >= 5.9.1 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch
--> Processing Dependency: rubygem-mixlib-log >= 1.7.1 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch
--> Processing Dependency: rubygem-puma >= 3.6.0 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch
--> Processing Dependency: rubygem-sinatra >= 1.4.5 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch
--> Processing Dependency: rubygem-tilt >= 1.4.1 for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch
--> Processing Dependency: rubygem-etcd for package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch
--> Finished Dependency Resolution
Error: Package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch (tendrl-tendrl)
           Requires: rubygem-bundler >= 1.13.6
           Installed: rubygem-bundler-1.7.8-3.el7.noarch (@base)
               rubygem-bundler = 1.7.8-3.el7
Error: Package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch (tendrl-tendrl)
           Requires: rubygem-mixlib-log >= 1.7.1
Error: Package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch (tendrl-tendrl)
           Requires: rubygem-etcd
Error: Package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch (tendrl-tendrl)
           Requires: rubygem-sinatra >= 1.4.5
Error: Package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch (tendrl-tendrl)
           Requires: rubygem-tilt >= 1.4.1
Error: Package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch (tendrl-tendrl)
           Requires: rubygem-puma >= 3.6.0
Error: Package: tendrl-api-1.2.3-05_02_2017_19_43_13.noarch (tendrl-tendrl)
           Requires: rubygem-minitest >= 5.9.1
           Available: rubygem-minitest-4.3.2-29.el7.noarch (base)
               rubygem-minitest = 4.3.2-29.el7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest```

Any ideas what is wrong?

**Comment by r0h4n** [comment]
@anivargi @TimothyAsir @brainfunked check this out

**Comment by japplewhite** [comment]
@andrewlove you should switch to using the usmqe-setup tendrl* playbooks in the short term. They are going to become the source for the final tendrl-ansible deployment of Tendrl. We will merge just the necessary pieces to the tendrl-ansible repo but that has not happened yet.

**Comment by mbukatov** [comment]
Installation of `tendrl-api` service is part of `tendrl-server` role and works with latest stable release:

```
[root@mbukatov-usm1-server ~]# rpm -qa tendrl*
tendrl-commons-1.4.1-2.el7.centos.noarch
tendrl-api-httpd-1.4.1-1.el7.centos.noarch
tendrl-node-agent-1.4.1-2.el7.centos.noarch
tendrl-dashboard-1.4.1-1.el7.centos.noarch
tendrl-performance-monitoring-1.4.1-3.el7.centos.noarch
tendrl-alerting-1.4.1-1.el7.centos.noarch
tendrl-api-1.4.1-1.el7.centos.noarch
[root@mbukatov-usm1-server ~]# curl http://localhost/api/1.0/ping; echo
{"status":"Ok"}
[root@mbukatov-usm1-server ~]#
```

**Comment by warrenguerin** [comment]
Bringing this one up again, I have been fighting with this for ages:

TASK [tendrl-ansible.tendrl-server : Install tendrl-api] ****************************************************************************************************************************************************************
fatal: [devnfsclu01.laya.ie]: FAILED! => {"changed": true, "msg": "Error: Package: tendrl-api-1.6.3-4.el7.noarch (Default_Organization_Tendrl_Tendrl)\n           Requires: rubygem-etcd\nError: Package: tendrl-api-1.6.3-4.el7.noarch (Default_Organization_Tendrl_Tendrl)\n           Requires: rubygem-puma >= 3.6.0\n", "rc": 1, "results": ["Loaded plugins: enabled_repos_upload, package_upload, product-id, search-\n              : disabled-repos, subscription-manager\nResolving Dependencies\n--> Running transaction check\n---> Package tendrl-api.noarch 0:1.6.3-4.el7 will be installed\n--> Processing Dependency: rubygem-tzinfo >= 1.2.2 for package: tendrl-api-1.6.3-4.el7.noarch\n--> Processing Dependency: rubygem-tilt >= 1.4.1 for package: tendrl-api-1.6.3-4.el7.noarch\n--> Processing Dependency: rubygem-thread_safe >= 0.3.5 for package: tendrl-api-1.6.3-4.el7.noarch\n--> Processing Dependency: rubygem-sinatra >= 1.4.5 for package: tendrl-api-1.6.3-4.el7.noarch\n--> Processing Dependency: rubygem-rake >= 0.9.6 for package: tendrl-api-1.6.3-4.el7.noarch\n--> Processing Dependency: rubygem-rack-protection >= 1.5.3 for package: tendrl-api-1.6.3-4.el7.noarch\n--> Processing Dependency: rubygem-rack >= 1.6.4 for package: tendrl-api-1.6.3-4.el7.noarch\n--> Processing Dependency: rubygem-puma >= 3.6.0 for package: tendrl-api-1.6.3-4.el7.noarch\n--> Processing Dependency: rubygem-i18n >= 0.7.0 for package: tendrl-api-1.6.3-4.el7.noarch\n--> Processing Dependency: rubygem-builder >= 3.1.0 for package: tendrl-api-1.6.3-4.el7.noarch\n--> Processing Dependency: rubygem-bcrypt >= 3.1.10 for package: tendrl-api-1.6.3-4.el7.noarch\n--> Processing Dependency: rubygem-activesupport >= 4.2.6 for package: tendrl-api-1.6.3-4.el7.noarch\n--> Processing Dependency: rubygem-activemodel >= 4.2.6 for package: tendrl-api-1.6.3-4.el7.noarch\n--> Processing Dependency: rubygem-etcd for package: tendrl-api-1.6.3-4.el7.noarch\n--> Running transaction check\n---> Package rubygem-activemodel.noarch 0:4.2.6-3.el7 will be installed\n---> Package rubygem-activesupport.noarch 1:4.2.6-1.el7 will be installed\n---> Package rubygem-bcrypt.x86_64 0:3.1.10-6.el7 will be installed\n---> Package rubygem-builder.noarch 0:3.1.4-3.el7 will be installed\n---> Package rubygem-i18n.noarch 0:0.7.0-3.el7 will be installed\n---> Package rubygem-rack.noarch 1:1.6.4-2.el7 will be installed\n---> Package rubygem-rack-protection.noarch 0:1.5.3-3.el7 will be installed\n---> Package rubygem-rake.noarch 0:0.9.6-33.el7_4 will be installed\n---> Package rubygem-sinatra.noarch 1:1.4.8-2.el7 will be installed\n---> Package rubygem-thread_safe.noarch 0:0.3.5-2.el7 will be installed\n---> Package rubygem-tilt.noarch 0:2.0.7-1.el7 will be installed\n---> Package rubygem-tzinfo.noarch 0:1.2.2-3.el7 will be installed\n---> Package tendrl-api.noarch 0:1.6.3-4.el7 will be installed\n--> Processing Dependency: rubygem-puma >= 3.6.0 for package: tendrl-api-1.6.3-4.el7.noarch\n--> Processing Dependency: rubygem-etcd for package: tendrl-api-1.6.3-4.el7.noarch\n--> Finished Dependency Resolution\nError: Package: tendrl-api-1.6.3-4.el7.noarch (Default_Organization_Tendrl_Tendrl)\n           Requires: rubygem-etcd\nError: Package: tendrl-api-1.6.3-4.el7.noarch (Default_Organization_Tendrl_Tendrl)\n           Requires: rubygem-puma >= 3.6.0\n**********************************************************************\nDependency resolving failed due to missing dependencies.\nSome repositories on your system are disabled, but yum can enable them\nand search for missing dependencies. This will require downloading\nmetadata for disabled repositories and may take some time and traffic.\n**********************************************************************\n\n--> Running transaction check\n---> Package tendrl-api.noarch 0:1.6.3-4.el7 will be installed\n--> Processing Dependency: rubygem-puma >= 3.6.0 for package: tendrl-api-1.6.3-4.el7.noarch\n--> Processing Dependency: rubygem-etcd for package: tendrl-api-1.6.3-4.el7.noarch\n--> Finished Dependency Resolution\n You could try using --skip-broken to work around the problem\n You could try running: rpm -Va --nofiles --nodigest\nUploading Enabled Repositories Report\nLoaded plugins: product-id, subscription-manager\n"]}

RUNNING HANDLER [tendrl-ansible.tendrl-server : restart rsyslog] ********************************************************************************************************************************************************
        to retry, use: --limit @/root/site.retry

PLAY RECAP **************************************************************************************************************************************************************************************************************
devnfsclu01.laya.ie        : ok=17   changed=1    unreachable=0    failed=1

My version looks good:

[root@devnfsclu01 ~]# yum info tendrl-api.noarch
Loaded plugins: enabled_repos_upload, package_upload, product-id, search-disabled-repos, subscription-manager
Available Packages
Name        : tendrl-api
Arch        : noarch
Version     : 1.6.3
Release     : 4.el7
Size        : 40 k
Repo        : Default_Organization_Tendrl_Tendrl
Summary     : Collection of tendrl api extensions
URL         : https://github.com/Tendrl/api
License     : LGPLv2+
Description : Collection of tendrl api.

Uploading Enabled Repositories Report
Loaded plugins: product-id, subscription-manager
[root@devnfsclu01 ~]#

This is how far its gotten:

[root@devnfsclu01 ~]# yum list installed | grep tendrl
tendrl-ansible.noarch         1.6.3-2.el7.centos      @Default_Organization_Tendrl_Tendrl
tendrl-commons.noarch         1.6.3-6.el7             @Default_Organization_Tendrl_Tendrl
tendrl-node-agent.noarch      1.6.3-6.el7             @Default_Organization_Tendrl_Tendrl
tendrl-selinux.noarch         1.5.4-2.el7.centos      @Default_Organization_Tendrl_Tendrl
[root@devnfsclu01 ~]#

Im using RHEL7.4 with RHEL repo's, tendrl repo and EPEL7
